[project]
name = "keyripple"
version = "0.1.0"
description = "用midi文件生成钢琴演奏动画"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mathutils>=3.3.0",
    "mido>=1.3.3",
    "numpy>=2.2.6",
    "tqdm>=4.67.1",
]
